{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "myapp.serviceAccountName" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccount.annotations .Values.workloadIdentity.enabled }}
  annotations:
    {{- if .Values.workloadIdentity.enabled }}
    azure.workload.identity/client-id: {{ include "myapp.clientId" . | quote }}
    azure.workload.identity/tenant-id: {{ include "myapp.tenantId" . | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
