apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sidecar-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: sidecar-metrics
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      prometheus.io/scrape-sidecar: "true"
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: sidecar-metrics
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
      scheme: http
      relabelings:
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_pod_container_name]
          targetLabel: container
